# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import game_pb2 as game__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in game_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinLobby = channel.stream_stream(
                '/com.paddez.wordformed.GameService/JoinLobby',
                request_serializer=game__pb2.JoinLobbyRequest.SerializeToString,
                response_deserializer=game__pb2.JoinLobbyResponse.FromString,
                _registered_method=True)
        self.SubmitWord = channel.unary_unary(
                '/com.paddez.wordformed.GameService/SubmitWord',
                request_serializer=game__pb2.SubmitWordRequest.SerializeToString,
                response_deserializer=game__pb2.SubmitWordResponse.FromString,
                _registered_method=True)
        self.GetLeaderboard = channel.unary_unary(
                '/com.paddez.wordformed.GameService/GetLeaderboard',
                request_serializer=game__pb2.GetLeaderboardRequest.SerializeToString,
                response_deserializer=game__pb2.GetLeaderboardResponse.FromString,
                _registered_method=True)


class GameServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def JoinLobby(self, request_iterator, context):
        """Join a lobby and receive real-time updates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitWord(self, request, context):
        """Submit a word to the server for validation and scoring.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLeaderboard(self, request, context):
        """Get the current game leaderboard.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinLobby': grpc.stream_stream_rpc_method_handler(
                    servicer.JoinLobby,
                    request_deserializer=game__pb2.JoinLobbyRequest.FromString,
                    response_serializer=game__pb2.JoinLobbyResponse.SerializeToString,
            ),
            'SubmitWord': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitWord,
                    request_deserializer=game__pb2.SubmitWordRequest.FromString,
                    response_serializer=game__pb2.SubmitWordResponse.SerializeToString,
            ),
            'GetLeaderboard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLeaderboard,
                    request_deserializer=game__pb2.GetLeaderboardRequest.FromString,
                    response_serializer=game__pb2.GetLeaderboardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.paddez.wordformed.GameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.paddez.wordformed.GameService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def JoinLobby(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/com.paddez.wordformed.GameService/JoinLobby',
            game__pb2.JoinLobbyRequest.SerializeToString,
            game__pb2.JoinLobbyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.paddez.wordformed.GameService/SubmitWord',
            game__pb2.SubmitWordRequest.SerializeToString,
            game__pb2.SubmitWordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLeaderboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.paddez.wordformed.GameService/GetLeaderboard',
            game__pb2.GetLeaderboardRequest.SerializeToString,
            game__pb2.GetLeaderboardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
