# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x12\x15\x63om.paddez.wordformed\"1\n\x06Player\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x05\"%\n\x04Tile\x12\x0e\n\x06letter\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\"\x8d\x01\n\tGameState\x12.\n\x07players\x18\x01 \x03(\x0b\x32\x1d.com.paddez.wordformed.Player\x12*\n\x05tiles\x18\x02 \x03(\x0b\x32\x1b.com.paddez.wordformed.Tile\x12\x10\n\x08timer_ms\x18\x03 \x01(\x03\x12\x12\n\nis_started\x18\x04 \x01(\x08\"\'\n\x10JoinLobbyRequest\x12\x13\n\x0bplayer_name\x18\x01 \x01(\t\"\xbb\x01\n\x11JoinLobbyResponse\x12\x36\n\rplayer_joined\x18\x01 \x01(\x0b\x32\x1d.com.paddez.wordformed.PlayerH\x00\x12\x16\n\x0cgame_started\x18\x02 \x01(\x08H\x00\x12\x38\n\x0cstate_update\x18\x03 \x01(\x0b\x32 .com.paddez.wordformed.GameStateH\x00\x12\x13\n\tgame_over\x18\x04 \x01(\tH\x00\x42\x07\n\x05\x65vent\"4\n\x11SubmitWordRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x0c\n\x04word\x18\x02 \x01(\t\"R\n\x12SubmitWordResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x13\n\x0bscore_added\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x01(\t\"(\n\x15GetLeaderboardRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\"I\n\x16GetLeaderboardResponse\x12/\n\x08rankings\x18\x01 \x03(\x0b\x32\x1d.com.paddez.wordformed.Player2\xc3\x02\n\x0bGameService\x12\x62\n\tJoinLobby\x12\'.com.paddez.wordformed.JoinLobbyRequest\x1a(.com.paddez.wordformed.JoinLobbyResponse(\x01\x30\x01\x12\x61\n\nSubmitWord\x12(.com.paddez.wordformed.SubmitWordRequest\x1a).com.paddez.wordformed.SubmitWordResponse\x12m\n\x0eGetLeaderboard\x12,.com.paddez.wordformed.GetLeaderboardRequest\x1a-.com.paddez.wordformed.GetLeaderboardResponseB*\n\x1b\x63om.paddez.wordformed.protoB\tGameProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.paddez.wordformed.protoB\tGameProtoP\001'
  _globals['_PLAYER']._serialized_start=37
  _globals['_PLAYER']._serialized_end=86
  _globals['_TILE']._serialized_start=88
  _globals['_TILE']._serialized_end=125
  _globals['_GAMESTATE']._serialized_start=128
  _globals['_GAMESTATE']._serialized_end=269
  _globals['_JOINLOBBYREQUEST']._serialized_start=271
  _globals['_JOINLOBBYREQUEST']._serialized_end=310
  _globals['_JOINLOBBYRESPONSE']._serialized_start=313
  _globals['_JOINLOBBYRESPONSE']._serialized_end=500
  _globals['_SUBMITWORDREQUEST']._serialized_start=502
  _globals['_SUBMITWORDREQUEST']._serialized_end=554
  _globals['_SUBMITWORDRESPONSE']._serialized_start=556
  _globals['_SUBMITWORDRESPONSE']._serialized_end=638
  _globals['_GETLEADERBOARDREQUEST']._serialized_start=640
  _globals['_GETLEADERBOARDREQUEST']._serialized_end=680
  _globals['_GETLEADERBOARDRESPONSE']._serialized_start=682
  _globals['_GETLEADERBOARDRESPONSE']._serialized_end=755
  _globals['_GAMESERVICE']._serialized_start=758
  _globals['_GAMESERVICE']._serialized_end=1081
# @@protoc_insertion_point(module_scope)
